### ISSUE TITLE
Error when switching between episodes of a series.

### ISSUE THREAD

**Issue by markflaisz** [detarkende/stremio-ncore-addon#58]
Unfortunately, I often experience that when I try to switch between episodes of a series, the container doesn't respond, and I'm forced to restart it. The log shows the following error, and both version 0.7 and 0.8 behave similarly:

```
<-- GET /api/auth/qd5f5ekmglnpggvn5ekvxevpictdc4b4/stream
/series/tt6483832%3A3%3A19.json
--> GET /api/auth/qd5f5ekmglnpggvn5ekvxevpictdc4b4/stream
/series/tt6483832%3A3%3A19.json 200 223ms
<-- GET /api/auth/qd5f5ekmglnpggvn5ekvxevpictdc4b4/stream
/series/tt6483832%3A3%3A20.json
--> GET /api/auth/qd5f5ekmglnpggvn5ekvxevpictdc4b4/stream
/series/tt6483832%3A3%3A20.json 200 221ms
<-- GET /api/auth/qd5f5ekmglnpggvn5ekvxevpictdc4b4/stream
/play/ncore/3099210/0da2e15276bfbe1aedae415bd5c85c7ed1383
405/19
TypeError: terminated
    at Fetch.onAborted (node:internal/deps/undici/undici:
10815:53)
    at Fetch.emit (node:events:519:28)
    at Fetch.terminate (node:internal/deps/undici/undici:
9973:14)
    at Object.onError (node:internal/deps/undici/undici:1
0927:38)
    at Request.onError (node:internal/deps/undici/undici:
2079:31)
    at Object.errorRequest (node:internal/deps/undici/und
ici:1576:17)
    at Socket.<anonymous> (node:internal/deps/undici/undi
ci:6045:16)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:339:12)
    at TCP.callbackTrampoline (node:internal/async_hooks:
130:17) {
  [cause]: BodyTimeoutError: Body Timeout Error
      at Timeout.onParserTimeout [as callback] (node:inte
rnal/deps/undici/undici:5979:32)
      at Timeout.onTimeout [as _onTimeout] (node:internal
/deps/undici/undici:2356:17)
      at listOnTimeout (node:internal/timers:581:17)
      at process.processTimers (node:internal/timers:519:
7) {
    code: 'UND_ERR_BODY_TIMEOUT'
  }
}
--> GET /api/auth/qd5f5ekmglnpggvn5ekvxevpictdc4b4/stream
/play/ncore/3099210/0da2e15276bfbe1aedae415bd5c85c7ed1383
405/20 500 300s
```

**Comment by detarkende** [comment]
@flajszi - Can you please try version `0.9.0-pre-release`? I added a 5s timeout to the ncore requests, plus better logs, hopefully it should fix this issue, or at the very least, give us a better idea of what exactly goes wrong.

**Comment by markflaisz** [comment]
@detarkende 
Your timeout fix solved my problem again—thank you for your help!
I tested it by jumping between episodes about 40 times. The log only showed a single HTTP 406 error(~10times), but right after that, there was a “request completed” line, so as a user, I didn’t notice anything.

**Comment by markflaisz** [comment]
When I press the “Next Episode” button offered by the stremio app, the stream stops on the loading screen and doesn’t continue until I restart the addon. In the new log file and the live log, I don’t see anything unusual apart from the HTTP 406 / 500 code.

```
{"level":30,"time":1745270457297,"pid":1,"hostname":"stremio-ncore","msg":"Getting torrent info from torrent client for info hash \"56e938ff7a1281f923f8df71c6717e0cd4dfe3ea\""}
{"level":30,"time":1745270457300,"pid":1,"hostname":"stremio-ncore","msg":"Torrent with info hash \"56e938ff7a1281f923f8df71c6717e0cd4dfe3ea\" found."}
{"level":30,"time":1745270457304,"pid":1,"hostname":"stremio-ncore","method":"GET","path":"/api/auth/qd5f5ekmglnpggvn5ekvxevpictdc4b4/stream/play/ncore/3264090/56e938ff7a1281f923f8df71c6717e0cd4dfe3ea/7","userId":1,"duration":8,"status":206,"msg":"Request completed"}
{"level":30,"time":1745270457378,"pid":1,"hostname":"stremio-ncore","msg":"Getting torrent info from torrent client for info hash \"56e938ff7a1281f923f8df71c6717e0cd4dfe3ea\""}
{"level":30,"time":1745270457381,"pid":1,"hostname":"stremio-ncore","msg":"Torrent with info hash \"56e938ff7a1281f923f8df71c6717e0cd4dfe3ea\" found."}
{"level":30,"time":1745270457383,"pid":1,"hostname":"stremio-ncore","method":"GET","path":"/api/auth/qd5f5ekmglnpggvn5ekvxevpictdc4b4/stream/play/ncore/3264090/56e938ff7a1281f923f8df71c6717e0cd4dfe3ea/7","userId":1,"duration":6,"status":206,"msg":"Request completed"}
{"level":30,"time":1745270457412,"pid":1,"hostname":"stremio-ncore","msg":"Getting torrent info from torrent client for info hash \"56e938ff7a1281f923f8df71c6717e0cd4dfe3ea\""}
{"level":30,"time":1745270457415,"pid":1,"hostname":"stremio-ncore","msg":"Torrent with info hash \"56e938ff7a1281f923f8df71c6717e0cd4dfe3ea\" found."}
{"level":30,"time":1745270457626,"pid":1,"hostname":"stremio-ncore","msg":"Getting torrent info from torrent client for info hash \"56e938ff7a1281f923f8df71c6717e0cd4dfe3ea\""}
{"level":30,"time":1745270457629,"pid":1,"hostname":"stremio-ncore","msg":"Torrent with info hash \"56e938ff7a1281f923f8df71c6717e0cd4dfe3ea\" found."}
{"level":30,"time":1745270490799,"pid":1,"hostname":"stremio-ncore","searchCriteria":{"imdbId":"tt6483832","type":"series","season":4,"episode":8},"msg":"Looking for torrents on nCore"}
{"level":30,"time":1745270490936,"pid":1,"hostname":"stremio-ncore","searchCriteria":{"imdbId":"tt6483832","type":"series","season":4,"episode":8},"msg":"Found 4 torrents"}
{"level":30,"time":1745270490984,"pid":1,"hostname":"stremio-ncore","method":"GET","path":"/api/auth/qd5f5ekmglnpggvn5ekvxevpictdc4b4/stream/series/tt6483832%3A4%3A8.json","userId":1,"duration":187,"status":200,"msg":"Request completed"}
{"level":30,"time":1745270491004,"pid":1,"hostname":"stremio-ncore","msg":"Getting torrent info from torrent client for info hash \"56e938ff7a1281f923f8df71c6717e0cd4dfe3ea\""}
{"level":30,"time":1745270491007,"pid":1,"hostname":"stremio-ncore","msg":"Torrent with info hash \"56e938ff7a1281f923f8df71c6717e0cd4dfe3ea\" found."}
{"level":30,"time":1745270491009,"pid":1,"hostname":"stremio-ncore","method":"HEAD","path":"/api/auth/qd5f5ekmglnpggvn5ekvxevpictdc4b4/stream/play/ncore/3264090/56e938ff7a1281f923f8df71c6717e0cd4dfe3ea/7","userId":1,"duration":6,"status":416,"msg":"Request completed"}
{"level":30,"time":1745270491020,"pid":1,"hostname":"stremio-ncore","msg":"Getting torrent info from torrent client for info hash \"56e938ff7a1281f923f8df71c6717e0cd4dfe3ea\""}
{"level":30,"time":1745270491023,"pid":1,"hostname":"stremio-ncore","msg":"Torrent with info hash \"56e938ff7a1281f923f8df71c6717e0cd4dfe3ea\" found."}
{"level":30,"time":1745270491026,"pid":1,"hostname":"stremio-ncore","method":"GET","path":"/api/auth/qd5f5ekmglnpggvn5ekvxevpictdc4b4/stream/play/ncore/3264090/56e938ff7a1281f923f8df71c6717e0cd4dfe3ea/7","userId":1,"duration":7,"status":206,"msg":"Request completed"}
{"level":30,"time":1745270491053,"pid":1,"hostname":"stremio-ncore","msg":"Getting torrent info from torrent client for info hash \"56e938ff7a1281f923f8df71c6717e0cd4dfe3ea\""}
{"level":30,"time":1745270491056,"pid":1,"hostname":"stremio-ncore","msg":"Torrent with info hash \"56e938ff7a1281f923f8df71c6717e0cd4dfe3ea\" found."}
{"level":30,"time":1745270491058,"pid":1,"hostname":"stremio-ncore","method":"GET","path":"/api/auth/qd5f5ekmglnpggvn5ekvxevpictdc4b4/stream/play/ncore/3264090/56e938ff7a1281f923f8df71c6717e0cd4dfe3ea/7","userId":1,"duration":6,"status":206,"msg":"Request completed"}
{"level":30,"time":1745270491105,"pid":1,"hostname":"stremio-ncore","msg":"Getting torrent info from torrent client for info hash \"56e938ff7a1281f923f8df71c6717e0cd4dfe3ea\""}
{"level":30,"time":1745270491108,"pid":1,"hostname":"stremio-ncore","msg":"Torrent with info hash \"56e938ff7a1281f923f8df71c6717e0cd4dfe3ea\" found."}
{"level":30,"time":1745270491364,"pid":1,"hostname":"stremio-ncore","msg":"Getting torrent info from torrent client for info hash \"56e938ff7a1281f923f8df71c6717e0cd4dfe3ea\""}
{"level":30,"time":1745270491367,"pid":1,"hostname":"stremio-ncore","msg":"Torrent with info hash \"56e938ff7a1281f923f8df71c6717e0cd4dfe3ea\" found."}
{"level":30,"time":1745270583148,"pid":1,"hostname":"stremio-ncore","method":"GET","path":"/api/auth/qd5f5ekmglnpggvn5ekvxevpictdc4b4/stream/play/ncore/3264090/56e938ff7a1281f923f8df71c6717e0cd4dfe3ea/7","userId":1,"duration":299998,"status":500,"msg":"Request completed"}
{"level":30,"time":1745270583641,"pid":1,"hostname":"stremio-ncore","method":"GET","path":"/api/auth/qd5f5ekmglnpggvn5ekvxevpictdc4b4/stream/play/ncore/3264090/56e938ff7a1281f923f8df71c6717e0cd4dfe3ea/7","userId":1,"duration":300280,"status":500,"msg":"Request completed"}

```

**Comment by markflaisz** [comment]
@detarkende

Hi all! I tested the temporary version made by hewdrey. In that version, this error disappears—likely thanks to the HLS Stream Support, everything seems to work correctly. The issue still persists in version 0.9.0-pre-release-2.  have to restart the container every single time I start a new episode. (only on Android TV)

@hewdrey 
That said, fast-forward/seek doesn't work with this version on Android TV…
hewdrey/stremio-ncore-addon:latest

**Comment by hewdrey** [comment]
You're right, @flajszi — the HLS stream from my solution is quite unstable and doesn't perform very well.

Stremio’s approach to HLS conversion is significantly better, likely because they’ve had more time to refine it. However, it’s currently only available when you're using a format or device that Stremio considers unsupported. Unfortunately, we can’t force Stremio to convert to HLS on Android TV. I asked if they could add a field to override this behavior, but the response I received was this:  https://github.com/Stremio/stremio-bugs/issues/1262

From what I understand, the main reason seeking doesn’t work in my version is because Stremio uses a custom ffmpeg implementation via Jellyfin (https://github.com/Stremio/server-docker/blob/main/Dockerfile#L38)
which includes a unique “stream” type.

In contrast, standard ffmpeg — which I’m using — supports two types: event (for live streams) and vod (for video on demand). I’m using the vod type, but with a workaround: I manually generate the m3u8 files so Stremio can access the content while the server is still downloading and converting it. Normally, vod only produces the m3u8 playlist after all segments are ready, which takes too long.

If you can improve on my solution, or with looking into Stremio server.js implementation, you or somebody know a fix, that would be great. :) 

(I have also one other issue that subtitles are not loading somehow even if i set an m3u8 file to that.)

But in general, it's my solution to Android TV, it has nothing to do with detarkende and also it's very spaghetti code, as this was required to make it work somehow.

Of course, the best option would be if there were an option in stremio to convert it.
I don't expect @detarkende to make such solution, it's out of scope.

Also, for me, currently version 0.8.0 is not working, because it hangs too many times. I am using 0.7.0 with webtorrent. That is much more better for me at least, but I am running this on an ARM server.

I plan to continue support with my temporary release detarkende versions until this repository reaches 1.0.0.

But hopefully somehow after several rewrite of the stremio, as they are heavily working on this, this issue will be fixed on Android TVs.

For the "hungarian library" part, we discussed with @detarkende, we will try to separate it into another project, and possibly make a CDN, so everybody could reach it easily, but i had some issues with this in the past weeks with this. I am still trying to figure out a way how this could be working.
